name: VMCreativeLimit
main: Zeao\VMLimited\Main
version: 1.0.0
api: [3.0.0-ALPHA5]
author: Zeao
description: Limits creative mode. (Custom plugin.)
commands:
    creative:
        usage: /gmc
        description: Changes gamemode to creative.
    survival:
        usage: /gms
        description: Changes gamemode to survival
permissions:
    vmlimit.creative:
        default: op
        description: Lets you use /gmc
    vmlimit.survival:
        default: op
        description: Lets you use /gms